--- 
- hosts: all
  gather_facts: False
  user: ec2-user
  become: true
#  become_method: sudo
  tasks:
 
#downlaoding a tomcattar zip
  - name: to make sure wget is installed
    yum: name=wget state=installed
    
  - name: to download tarzip of tomcat using command module
    shell: | 
      cd ~
      mkdir towget
      cd towget
      wget 
      cd
   - name: to install tomcat 7
     yum: name=tomcat7 state=installed
     
   - name: to install the tomcat other directories
     command: yum install tomcat7-webapps tomcat7-docs-webapp tomcat7-admin-webapps -y
 
  
  
  - name: Deploy War File
    maven_artifact: group_id=org.sandeep artifact_id=application extension=war repository_url=http://ec2-54-244-176-121.us-west-2.compute.amazonaws.com:8080/nexus-2.14.7-01/content/repositories/snapshots/ username=admin password=admin123  dest=~/cd/
  

  - name: command module to copy to webapps
    command: docker cp ~/cd/application-latest.war tomcat:/usr/local/tomcat/webapps/
    
    
  - name: to restart tomcat docker container after the deployment
    command: docker restart tomcat
