--- 
- hosts: all
  gather_facts: False
  user: ec2-user
  become: true
#  become_method: sudo
  tasks:
  - name: Deploy War File
    maven_artifact: group_id=org.sandeep artifact_id=application extension=war repository_url=http://ec2-54-244-176-121.us-west-2.compute.amazonaws.com:8080/nexus-2.14.7-01/content/repositories/snapshots/ username=admin password=admin123  dest=~/cd/
  

  - name: command module to copy to webapps
    command: docker cp ~/cd/application-latest.war tomcat:/usr/local/tomcat/webapps/
    
    
  - name: to restart tomcat docker container after the deployment
    command: docker restart tomcat
